# Server settings
server:
    port: 8090

# spring
spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://localhost:3306/boya_platform?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            maxActiv: 20
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
            web-stat-filter:
                exclusions: stat
    http:
      encoding:
        charset: utf-8
        enabled: true
        force: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boya.platform.marineonline.model.po

# mapper
mapper:
    not-empty: false
    identity: MYSQL

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# spring cloud
eureka:
  client:
    serverUrl:
      dafaultZone: http://localhost:8761/eureka/

