server:
  port: 8761

eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://discovery:${server.port}/eureka/


