server:
  port: 8080

spring:
  cloud:
    config:
      uri: http://configserver:8888/
      name: configserver

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true