server:
  port: 2101

spring:
  cloud:
    config:
      name: eureka-consumer

eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

# 启用hystrix对feign的支持
feign:
  hystrix:
    enabled: true
